fig bug

diff --git a/scripts/atsrun b/scripts/atsrun
--- a/scripts/atsrun
+++ b/scripts/atsrun
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-Version_atsrun="2.1.9"
+Version_atsrun="2.2.0"
 
 # Get shared function
 ! source "SharedFunc" 2>/dev/null && echo "SharedFunc: No such file or directory" && exit 1
@@ -726,8 +726,12 @@ function control_autosub() {
 					false
 			fi
 		fi
-		if [[ $? -ne 0 ]] || [[ ! -f "$filepath/$name.$F" ]] || [[ "$Auto_Translate" == "yes" ]] ;then
+		if [[ $? -ne 0 ]] && [[ ! -f "$filepath/$name.$F" ]] && [[ "$Auto_Translate" == "yes" ]];then
 			WARNING "[$filename] Translate Subtitle [$name.$S_code.$F] Processing Fail" "$script_name"
+			echo "$filename" >> "$autosubfail"
+			((num_check_FAIL+=1))
+		elif [[ ! -f "$filepath/$name.$S_code.$F" ]] && [[ "$Auto_Translate" == "no" ]] ;then
+			WARNING "[$filename]Can not found resuft '$name.$S_code.$F'. Autosub [$name.$S_code.$F] Processing Fail" "$script_name"
 			echo "$filename" >> "$autosubfail"
 			((num_check_FAIL+=1))
 		else
